# Generated by Django 3.2.12 on 2023-12-12 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_room_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeetingRoom',
        ),
    ]
