# Generated by Django 3.2.12 on 2023-12-12 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_delete_meetingroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='link',
        ),
    ]
