# Generated by Django 3.2.12 on 2023-12-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_remove_room_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
