# Generated by Django 3.2.12 on 2023-12-13 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0008_meetingmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetingmessage',
            options={'verbose_name_plural': 'Message'},
        ),
        migrations.RemoveField(
            model_name='meetingmessage',
            name='room',
        ),
        migrations.RemoveField(
            model_name='meetingmessage',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='meetingmessage',
            name='user_name',
        ),
        migrations.AddField(
            model_name='meetingmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meetingmessage',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetingmessage',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetingmessage',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sender_messages', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meetingmessage',
            name='message',
            field=models.CharField(max_length=1000),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=1000)),
                ('bio', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='user_images')),
                ('verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
