# Generated by Django 3.2.12 on 2023-12-13 11:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0009_auto_20231213_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetingmessage',
            options={'ordering': ['date'], 'verbose_name_plural': 'Message'},
        ),
        migrations.AddField(
            model_name='meetingmessage',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 12, 13, 11, 31, 32, 962202, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meetingmessage',
            name='message',
            field=models.CharField(max_length=10000000000),
        ),
        migrations.AlterField(
            model_name='meetingmessage',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meetingmessage',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meetingmessage',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
